# Generated by Django 4.2.2 on 2023-07-04 17:08

from django.db import migrations
import users.mangers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.mangers.UserManager()),
            ],
        ),
    ]
