# Generated by Django 4.2.2 on 2023-07-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('product_name', models.TextField()),
                ('count', models.TextField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
            options={
                'db_table': 'savat',
            },
        ),
        migrations.CreateModel(
            name='Sorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('mahsulot_zakasi', models.IntegerField()),
            ],
            options={
                'db_table': 'sorov',
            },
        ),
    ]
