# Generated by Django 4.2.2 on 2023-06-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ordering",
                    models.PositiveIntegerField(default=0, verbose_name="ordering"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "short_name",
                    models.CharField(max_length=100, verbose_name="short name"),
                ),
                (
                    "short_name_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="short name"
                    ),
                ),
                (
                    "short_name_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="short name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ordering",
                    models.PositiveIntegerField(default=0, verbose_name="ordering"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="regular price"
                    ),
                ),
                ("image", models.ImageField(upload_to="images/%Y/%m/%d/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("ordering", "-id"),
            },
        ),
    ]
